//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sale_system_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public string custName { get; set; }
        public string typeNum { get; set; }
        public string fixDate { get; set; }
        public string salePrice { get; set; }
        public string changeDate { get; set; }
        public string LvXing1_Last { get; set; }
        public string LvXing2_Last { get; set; }
        public string LvXing3_Last { get; set; }
        public string LvWang1_Last { get; set; }
        public string LvWang2_Last { get; set; }
        public string LvWang3_Last { get; set; }
        public string LvWang4_Last { get; set; }
        public string MoreInfo { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
